export const CREATE_REMINDER = "CREATE_REMINDER";
export const UPDATE_REMINDER = "UPDATE_REMINDER";
export const DELETE_REMINDER = "DELETE_REMINDER";
export const CALENDAR_PREV_MONTH = "CALENDAR_PREV_MONTH";
export const CALENDAR_NEXT_MONTH = "CALENDAR_NEXT_MONTH";
